name: Stable build
on:
  push:
    branches:
      - stable
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  get-props:
    name: Get Props
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.version }}
      repo_url: ${{ steps.get-repo-url.outputs.repo_url }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Get Version
        id: get-version
        run: echo "version=$(grep -oE '<Version>[^<]+' src/Avayomi/Avayomi.csproj | sed 's/<Version>//')" >> $GITHUB_OUTPUT

      - name: Get Repo Url
        id: get-repo-url
        run: echo "repo_url=${{ github.server_url }}/${{ github.repository }}" >> $GITHUB_OUTPUT
  
  build:
    name: Build Avayomi
    needs: get-props
    strategy:
      fail-fast: true
      matrix:
        target-platform:
          - windows
          - linux
        target-arch:
          - x64
        include:
          - target-platform: windows
            os: windows-latest
            channel: win-x64
          - target-platform: linux
            os: ubuntu-latest
            channel: linux-x64
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      DOTNET_NOLOGO: true
      NUGET_CERT_REVOCATION_MODE: offline
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Check Cache
        id: check-cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.nuget/packages
            ~/.dotnet/toolResolverCache
            ~/.dotnet/tools
            ${{ github.workspace }}/.config
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget

      - name: Install FUSE
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo add-apt-repository universe
          sudo apt install libfuse2

      - name: Install Velopack
        if: ${{ steps.check-cache.outputs.cache-hit == false }}
        run: |
          dotnet new tool-manifest
          dotnet tool install vpk

      - name: Restore
        if: ${{ steps.check-cache.outputs.cache-hit == false }}
        run: dotnet restore

      - name: Publish
        run: dotnet publish src/Avayomi/Avayomi.csproj -c Release -o publish

      - name: Download Previous Release
        run: dotnet vpk download github --repoUrl ${{ needs.get-props.outputs.repo_url }} -c ${{ matrix.channel }} --token ${{ secrets.GITHUB_TOKEN }}

      - name: Pack Release
        shell: bash
        run: >
          dotnet vpk pack  
          -u Avayomi  
          -v ${{ needs.get-props.outputs.version }}  
          -p publish 
          -c ${{ matrix.channel }}  
          ${{ matrix.target-platform == 'linux' && '-i src/Avayomi/Assets/faviconlogo.png' || '' }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.channel }}-build
          path: |
            Releases/
            !Releases/RELEASES-*
  
  release:
    name: Release
    needs:
      - get-props
      - build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: Releases
          merge-multiple: true

      - name: Install Velopack
        if: ${{ steps.check-cache.outputs.cache-hit == false }}
        run: |
          dotnet new tool-manifest
          dotnet tool install vpk

      - name: Windows Release
        run: >
          dotnet vpk upload github 
          --channel win-x64
          --outputDir Releases
          --repoUrl ${{ needs.get-props.outputs.repo_url }} 
          --tag v${{ needs.get-props.outputs.version }}
          --releaseName "Stable Build v${{ needs.get-props.outputs.version }}"
          --token ${{ secrets.GITHUB_TOKEN }}
          --publish

      - name: Linux Release
        run: >
          dotnet vpk upload github 
          --channel win-x64
          --outputDir Releases
          --repoUrl ${{ needs.get-props.outputs.repo_url }} 
          --tag v${{ needs.get-props.outputs.version }}
          --releaseName "Stable Build v${{ needs.get-props.outputs.version }}"
          --token ${{ secrets.GITHUB_TOKEN }}
          --publish
          --merge