name: Dev build
on:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Avayomi
    strategy:
      fail-fast: true
      matrix:
        target-platform:
          - windows
          - linux
        target-arch:
          - x64
        include:
          - target-platform: windows
            os: windows-latest
            channel: win-x64-dev
          - target-platform: linux
            os: ubuntu-latest
            channel: linux-x64-dev
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      DOTNET_NOLOGO: true
      NUGET_CERT_REVOCATION_MODE: offline
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check Cache
        id: check-cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.nuget
            ~/.dotnet
            ${{ github.workspace }}/.config
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json', '**/*.csproj') }}

      - name: Install Velopack
        run: dotnet tool install vpk --prerelease --create-manifest-if-needed

      - name: Restore
        run: dotnet restore

      - name: Get Version
        id: get-version
        run: echo "version=$(grep -oE '<Version>[^<]+' Directory.Build.props | sed 's/<Version>//')-dev.${{ github.run_number }}" >> $GITHUB_OUTPUT

      - name: Publish
        run: dotnet publish src/Desktop/Desktop.csproj -c Release -o publish -p:Version=${{ steps.get-version.outputs.version }}

      - name: Download Previous Release
        run: >
          dotnet vpk download github 
          --pre 
          --repoUrl 
          ${{ github.server_url }}/${{ github.repository }} 
          -c ${{ matrix.channel }} 
          --token ${{ secrets.GITHUB_TOKEN }}

      - name: Pack Release
        shell: bash
        run: >
          dotnet vpk pack  
          -u Avayomi  
          -v ${{ steps.get-version.outputs.version }}  
          -p publish 
          -c ${{ matrix.channel }}  
          -e Desktop${{ matrix.target-platform == 'windows-latest' && '.exe' || '' }}
          -i src/Desktop/Assets/faviconlogo.${{ matrix.os == 'windows-latest' && 'ico' || 'png' }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.channel }}-build
          path: |
            Releases/
            !Releases/RELEASES-*
  
  release:
    name: Release
    needs:
      - build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get Hash
        id: get-hash
        run: echo "hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: Releases
          merge-multiple: true

      - name: Delete Last Dev Build
        run: gh release delete dev-build -y --cleanup-tag
        continue-on-error: true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: Dev ${{ steps.get-hash.outputs.hash }}
          body_path: .github/dev-build-release.md
          prerelease: true
          draft: false
          tag_name: dev-build
          files: |
            Releases/*  